version: 2
jobs:

  build-and-test:

    docker:
      - image: cimg/php:8.0-node # alias for latest PHP 8.0.x release with Composer 2 and Node.js.
        environment:
          MYSQL_USER: root
          NODE_OPTIONS: --max-old-space-size=4096
      - image: cimg/mysql:8.0.28
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --port=3306
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_HOST: "127.0.0.1"
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: wordpress_test

    steps:
      - checkout
      - restore_cache:
          keys:
            - wp-tesla-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "composer.lock" }}
      - run:
          name: Build
          command: ./bin/build.sh
      - run:
          name: Run Tests
          command: ./bin/run-tests.sh
      - save_cache:
          key: wp-tesla-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "composer.lock" }}
          paths:
            - node_modules
            - vendor

  build-and-deploy:

    docker:
      - image: cimg/php:8.0-node # alias for latest PHP 8.0.x release with Composer 2 and Node.js.
        environment:
          MYSQL_USER: root
          NODE_OPTIONS: --max-old-space-size=4096
      - image: cimg/mysql:8.0.28
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --port=3306
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_HOST: "127.0.0.1"
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: wordpress_test

    steps:
      - checkout
      - restore_cache:
          keys:
            - wp-tesla-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "composer.lock" }}
      - add_ssh_keys:
          fingerprints:
            - "f3:0b:d0:fa:3c:cc:95:b8:c7:59:c9:ac:39:52:85:48"
      - run:
          name: Build
          command: ./bin/build.sh
      - run:
          name: Run Tests
          command: ./bin/run-tests.sh
      - run:
          name: Deploy
          command: ./bin/deploy.sh
      - save_cache:
          key: wp-tesla-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "composer.lock" }}
          paths:
            - node_modules
            - vendor

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - trunk
                - develop
