version: 2
jobs:

  build-and-deploy:

    docker:
      - image: circleci/php:7.4-node-browsers
        environment:
          MYSQL_USER: root
          MYSQL_PASSWORD: password
      - image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
        environment:
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          MYSQL_ALLOW_EMPTY_PASSWORD: true

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "f3:0b:d0:fa:3c:cc:95:b8:c7:59:c9:ac:39:52:85:48"
      - run:
          name: Build
          command: ./bin/build.sh
      - run:
          name: Test
          command: ./bin/test.sh
      - run:
          name: Deploy
          command: ./bin/deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - master
                - develop
                - feature/circleci-unit-tests
