version: 2
jobs:

  build-and-deploy:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "f3:0b:d0:fa:3c:cc:95:b8:c7:59:c9:ac:39:52:85:48"
      - run:
          name: Build
          command: ./bin/build.sh
      - run:
          name: Deploy
          command: ./bin/deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - master
                - feature/circleci-deployment
