version: 2
jobs:

  build-and-deploy:

    docker:
      - image: circleci/php:7.3.0-cli-stretch-node
        environment:
          MYSQL_USER: root
      - image: circleci/mysql:5.7.30
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --port=3306
        ports:
          - "3306:3306"
        environment:
          MYSQL_USER: root
          MYSQL_HOST: "127.0.0.1"
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: wordpress_test

    steps:
      - checkout
      - restore_cache:
          keys:
            - wp-tesla-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "composer.lock" }}
      - add_ssh_keys:
          fingerprints:
            - "f3:0b:d0:fa:3c:cc:95:b8:c7:59:c9:ac:39:52:85:48"
      - run:
          name: Install Tests
          command: ./bin/install-tests.sh
      - run:
          name: Build
          command: ./bin/build.sh
      - run:
          name: Run Tests
          command: ./bin/run-tests.sh
      - run:
          name: Deploy
          command: ./bin/deploy.sh
      - save_cache:
          key: wp-tesla-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "composer.lock" }}
          paths:
            - node_modules
            - vendor

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - master
                - develop
                - feature/circleci-unit-tests
